version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "surveyapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nc762hufu3vw"
s3_prefix = "surveyapi"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
