AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  survey-api

  Sample SAM Template for survey-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  SurveyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: surveys
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  ClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: clients
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
        - AttributeName: survey_id
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
        - AttributeName: survey_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  SendSurveySNSTopic:
    Type: AWS::SNS::Topic

  SurveyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: surveys/
      Handler: surveys.surveys_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref SurveyTable
      Events:
        ListSurveys:
          Type: Api
          Properties:
            Path: /surveys
            Method: get
        CreateSurvey:
          Type: Api
          Properties:
            Path: /surveys
            Method: post
        GetSurvey:
          Type: Api
          Properties:
            Path: /surveys/{id}
            Method: get

  ClientSurveyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: surveys/
      Handler: clients.clients_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref ClientsTable
        - DynamoDBReadPolicy:
            TableName:
              !Ref SurveyTable
        - SNSPublishMessagePolicy:
            TopicName: 
              !GetAtt SendSurveySNSTopic.TopicName
      # Environment:
      #   Variables:
      #     SNStopic: !Ref SendSurveySNSTopic
      Events:
        ListClients:
          Type: Api
          Properties:
            Path: /clients
            Method: get
        GetClient:
          Type: Api
          Properties:
            Path: /clients/{client_id}
            Method: get
        CreateClient:
          Type: Api
          Properties:
            Path: /clients
            Method: post
        ListClientSurveys:
          Type: Api
          Properties:
            Path: /clients/{client_id}/surveys
            Method: get
        # AddSurveyToClient:
        #   Type: Api
        #   Properties:
        #     Path: /clients/{client_id}/surveys/{survey_id}
        #     Method: put
        SendClientSurvey:
          Type: Api
          Properties:
            Path: /clients/{client_id}/surveys/{survey_id}
            Method: post
        GetClientSurvey:
          Type: Api
          Properties:
            Path: /clients/{client_id}/surveys/{survey_id}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SurveyApi:
    Description: "API Gateway endpoint URL for Prod stage for Survey API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/surveys/"
  SurveyFunction:
    Description: "Surveys Lambda Function ARN"
    Value: !GetAtt SurveyFunction.Arn
  SurveyFunctionIamRole:
    Description: "Implicit IAM Role created for Surveys function"
    Value: !GetAtt SurveyFunctionRole.Arn
  ClientSurveyFunction:
    Description: ClientSurveyFunction function name
    Value: !Ref ClientSurveyFunction
  SNStopicName:
    Description: SNS topic name
    Value: !GetAtt SendSurveySNSTopic.TopicName
  SNStopicARN:
    Description: SNS topic ARN
    Value: !Ref SendSurveySNSTopic